debug: false
exp_name: "exp009"
model_name: "seresnext50_32x4d"
device_id: 0
batch_size: 80
img_size: 512
n_workers: 10
n_epochs: 15
transform: true
load_checkpoint:
  - "/workspace/output/exp009/model/cv0_weight_checkpoint14.pth"
  - "/workspace/output/exp009/model/cv1_weight_checkpoint15.pth"
  - "/workspace/output/exp009/model/cv2_weight_checkpoint15.pth"
  - "/workspace/output/exp009/model/cv3_weight_checkpoint11.pth"
  - "/workspace/output/exp009/model/cv4_weight_checkpoint10.pth"

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train.csv"
