debug: false
exp_name: "exp022"
model_name: "resnest101e"
device_id: 0
batch_size: 24
img_size: 512
n_workers: 4
n_epochs: 30
start_epoch: 1
transform: true
load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train2.csv"
img_dir: "/data/train1280"

accumulation_steps: 0
early_stopping_steps: 5
freeze_bn: false

clahe: false
mix: false