debug: false
exp_name: "exp018_2"
model_name: "resnet200d"
device_id: 0
batch_size: 16
img_size: 512
n_workers: 4
n_epochs: 30
start_epoch: 0
transform: true
load_checkpoint:
  - "/workspace/output/exp016/model/cv0_weight_checkpoint0.pth"
  - "/workspace/output/exp016/model/cv1_weight_checkpoint0.pth"
  - "/workspace/output/exp016/model/cv2_weight_checkpoint7.pth"
  - "/workspace/output/exp016/model/cv3_weight_checkpoint5.pth"
  - "/workspace/output/exp016/model/cv4_weight_checkpoint7.pth"

hold_out:
  - 2

df_train_path: "/data/df_train2.csv"

accumulation_steps: 4
early_stopping_steps: 5
freeze_bn: true

clahe: true