debug: false
exp_name: "exp009"
model_name: "seresnext50_32x4d"
device_id: 0
batch_size: 48
img_size: 512
n_workers: 10
n_epochs: 15
transform: true
load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train.csv"
