debug: false
exp_name: "exp009"
model_name: "seresnext50_32x4d"
device_id: 0
batch_size: 48
img_size: 512
n_workers: 4
n_epochs: 30
start_epoch: 1
transform: true
load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train2.csv"

accumulation_steps: 2
early_stopping_steps: 5
freeze_bn: false