debug: false
exp_name: "cvc_exp007_3rd"
#model_name: "resnest101e"
model_name: "resnest50d"
device_id: 0
batch_size: 32
img_size: 512
n_workers: 4
n_epochs: 30
start_epoch: 1
transform: true
load_checkpoint:
  - "/workspace/output_cvc/cvc_exp007_2nd/model/cv0_weight_checkpoint21.pth"
  - "/workspace/output_cvc/cvc_exp007_2nd/model/cv1_weight_checkpoint26.pth"
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
#  - 2
#  - 3
#  - 4

df_train_path: "/data/df_train3.csv"
img_dir: "/data/train512"

accumulation_steps: 1
early_stopping_steps: 3
freeze_bn: false

clahe: false
mix: false