debug: false
exp_name: "cvc_exp107"
#model_name: "resnest101e"
model_name: "resnet200d"
device_id: 0
batch_size: 8
img_size: 600
n_workers: 4
n_epochs: 30
start_epoch: 1
transform: true
load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train3.csv"
img_dir: "/data/train512"

accumulation_steps: 1
early_stopping_steps: 4
freeze_bn: false

clahe: false
mix: false