debug: false
exp_name: "seg_exp001"
model_name: "resnet34"
device_id: 0
batch_size: 32
img_size: 512
n_workers: 4
n_epochs: 30
start_epoch: 0
transform: true
load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train2.csv"
img_dir: "/data/train1280"

accumulation_steps: 1
early_stopping_steps: 2
freeze_bn: false

clahe: false
mix: false