debug: false
exp_name: "exp001_2"
model_name: "seresnext50_32x4d"
device_id: 0
batch_size: 48
img_size: 512
n_workers: 10
n_epochs: 5
start_epoch: 9
transform: true
load_checkpoint:
  - "/workspace/output/exp001/model/cv0_weight_checkpoint8.pth"
  - "/workspace/output/exp001/model/cv1_weight_checkpoint8.pth"
  - "/workspace/output/exp001/model/cv2_weight_checkpoint8.pth"
  - "/workspace/output/exp001/model/cv3_weight_checkpoint8.pth"
  - "/workspace/output/exp001/model/cv4_weight_checkpoint8.pth"

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/data/df_train.csv"
